config/routes.rb
Untitled::Application.routes.draw do
  resources :starts

  resources :homes

  resources :doctors_offices

  resources :invoices

  resources :admins

  resources :diagnostics

  resources :appointments

  resources :physicians

  resources :patients

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :position, :username
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :person
  belongs_to :physician
  belongs_to :patient
  belongs_to :doctors_office
  has_many :invoices
  has_many :diagnostics, through: :invoices
  attr_protected :admin

  def person
    @patients = Patient.all
  end
  def doctor
    @physicians = Physician.all
  end
end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  has_many :invoices
  has_many :appointments, through: :invoices
  belongs_to :admin
  attr_protected :admin

end

app/models/doctors_office.rb
class DoctorsOffice < ActiveRecord::Base
  has_many :invoices
  has_many :appointments, through: :invoices
  attr_protected :admin

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :diagnostics
  belongs_to :appointment
  belongs_to :admin
  belongs_to :patient
  validate :patient, on: :create
  attr_protected :admin


  def active_patient
    errors.add(:patient_id, 'is not active') unless patient.active?
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
  attr_protected :admin

  def full_name
    "#{lastname} #{firstname}"

  end
  def patient_id
    "#{id} #{lastname} #{firstname}"
  end
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :Admin
  attr_protected :admin


  def full_name
    "#{firstname} #{lastname}"
  end

end

app/models/start.rb
class Start < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/new
  # GET /admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(params[:admin])

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admins/1
  # PUT /admins/1.json
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(params[:admin])
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to admins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  # GET /starts
  # GET /starts.json
  def index
    @starts = Start.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @starts }
    end
  end

  # GET /starts/1
  # GET /starts/1.json
  def show
    @start = Start.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @start }
    end
  end

  # GET /starts/new
  # GET /starts/new.json
  def new
    @start = Start.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @start }
    end
  end

  # GET /starts/1/edit
  def edit
    @start = Start.find(params[:id])
  end

  # POST /starts
  # POST /starts.json
  def create
    @start = Start.new(params[:start])

    respond_to do |format|
      if @start.save
        format.html { redirect_to @start, notice: 'Start was successfully created.' }
        format.json { render json: @start, status: :created, location: @start }
      else
        format.html { render action: "new" }
        format.json { render json: @start.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /starts/1
  # PUT /starts/1.json
  def update
    @start = Start.find(params[:id])

    respond_to do |format|
      if @start.update_attributes(params[:start])
        format.html { redirect_to @start, notice: 'Start was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @start.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starts/1
  # DELETE /starts/1.json
  def destroy
    @start = Start.find(params[:id])
    @start.destroy

    respond_to do |format|
      format.html { redirect_to starts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/doctors_offices_helper.rb
module DoctorsOfficesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/starts_helper.rb
module StartsHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.username %></td>
    <td><%= admin.position %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @admin.username %>
</p>

<p>
  <b>Position:</b>
  <%= @admin.position %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>