config/routes.rb
Untitled::Application.routes.draw do
  resources :starts

  resources :homes

  resources :doctors_offices

  resources :invoices

  resources :admins

  resources :diagnostics

  resources :appointments

  resources :physicians

  resources :patients

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :diagnostics
  belongs_to :appointment
  belongs_to :admin
  belongs_to :patient
  validate :patient, on: :create
  attr_protected :admin


  def active_patient
    errors.add(:patient_id, 'is not active') unless patient.active?
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(params[:invoice])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :diag_code %><br />
    <%= f.number_field :diag_code %>
  </div>
  <div class="field">
    <%= f.label :appoint_id %><br />
    <%= f.number_field :appoint_id %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br />
    <%= f.number_field :admin_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <tr>
    <th>Diag code</th>
    <th>Appoint</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invoices.each do |invoice| %>
  <tr>
    <td><%= invoice.diag_code %></td>
    <td><%= invoice.appoint_id %></td>
    <td><%= invoice.admin_id %></td>
    <td><%= link_to 'Show', invoice %></td>
    <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
    <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Diag code:</b>
  <%= @invoice.diag_code %>
</p>

<p>
  <b>Appoint:</b>
  <%= @invoice.appoint_id %>
</p>

<p>
  <b>Admin:</b>
  <%= @invoice.admin_id %>
</p>


<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>