config/routes.rb
Untitled::Application.routes.draw do
  resources :starts

  resources :homes

  resources :doctors_offices

  resources :invoices

  resources :admins

  resources :diagnostics

  resources :appointments

  resources :physicians

  resources :patients

end

app/models/doctors_office.rb
class DoctorsOffice < ActiveRecord::Base
  has_many :invoices
  has_many :appointments, through: :invoices
  attr_protected :admin

end

app/controllers/doctors_offices_controller.rb
class DoctorsOfficesController < ApplicationController
  # GET /doctors_offices
  # GET /doctors_offices.json
  def index
    @doctors_offices = DoctorsOffice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doctors_offices }
    end
  end

  # GET /doctors_offices/1
  # GET /doctors_offices/1.json
  def show
    @doctors_office = DoctorsOffice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doctors_office }
    end
  end

  # GET /doctors_offices/new
  # GET /doctors_offices/new.json
  def new
    @doctors_office = DoctorsOffice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doctors_office }
    end
  end

  # GET /doctors_offices/1/edit
  def edit
    @doctors_office = DoctorsOffice.find(params[:id])
  end

  # POST /doctors_offices
  # POST /doctors_offices.json
  def create
    @doctors_office = DoctorsOffice.new(params[:doctors_office])

    respond_to do |format|
      if @doctors_office.save
        format.html { redirect_to @doctors_office, notice: 'Doctors office was successfully created.' }
        format.json { render json: @doctors_office, status: :created, location: @doctors_office }
      else
        format.html { render action: "new" }
        format.json { render json: @doctors_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doctors_offices/1
  # PUT /doctors_offices/1.json
  def update
    @doctors_office = DoctorsOffice.find(params[:id])

    respond_to do |format|
      if @doctors_office.update_attributes(params[:doctors_office])
        format.html { redirect_to @doctors_office, notice: 'Doctors office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doctors_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors_offices/1
  # DELETE /doctors_offices/1.json
  def destroy
    @doctors_office = DoctorsOffice.find(params[:id])
    @doctors_office.destroy

    respond_to do |format|
      format.html { redirect_to doctors_offices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/doctors_offices_helper.rb
module DoctorsOfficesHelper
end

app/views/doctors_offices/_form.html.erb
<%= form_for(@doctors_office) do |f| %>
  <% if @doctors_office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctors_office.errors.count, "error") %> prohibited this doctors_office from being saved:</h2>

      <ul>
      <% @doctors_office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :officetitle %><br />
    <%= f.text_field :officetitle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors_offices/edit.html.erb
<h1>Editing doctors_office</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctors_office %> |
<%= link_to 'Back', doctors_offices_path %>

app/views/doctors_offices/index.html.erb
<h1>Listing doctors_offices</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Office Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @doctors_offices.each do |doctors_office| %>
  <tr>
    <td><%= doctors_office.name %></td>
    <td><%= doctors_office.officetitle %></td>
    <td><%= link_to 'Show', doctors_office %></td>
    <td><%= link_to 'Edit', edit_doctors_office_path(doctors_office) %></td>
    <td><%= link_to 'Destroy', doctors_office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Doctors office', new_doctors_office_path %>

app/views/doctors_offices/new.html.erb
<h1>New doctors_office</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_offices_path %>

app/views/doctors_offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @doctors_office.name %>
</p>

<p>
  <b>Officetitle:</b>
  <%= @doctors_office.officetitle %>
</p>


<%= link_to 'Edit', edit_doctors_office_path(@doctors_office) %> |
<%= link_to 'Back', doctors_offices_path %>